from ..mapdata import (
    GetLocationIndex,
    GetStringIndex,
    GetSwitchIndex,
    GetUnitIndex
)

from ..utils import u2b, b2i4


def EncodeAIScript(ais):
    if type(ais) is str:
        ais = u2b(ais)

    if type(ais) is bytes:
        assert len(ais) >= 4, 'AIScript name too short'

        if len(ais) > 4:
            return b2i4(AIScriptDict[ais])

        elif len(ais) == 4:
            return b2i4(ais)

    else:
        return ais


def EncodeLocation(loc):
    return GetLocationIndex(loc) + 1


def EncodeString(s):
    return GetStringIndex(s)


def EncodeSwitch(sw):
    return GetSwitchIndex(sw)


def EncodeUnit(u):
    return GetUnitIndex(u)


# Data from http://cafe.daum.net/rpgguild/6cWR/158
# Original data from ScAIEdit
AIScriptDict = {
    # Custom AI Scripts
    b'Terran Custom Level': b'TMCu',
    b'Zerg Custom Level': b'ZMCu',
    b'Protoss Custom Level': b'PMCu',
    b'Terran Expansion Custom Level': b'TMCx',
    b'Zerg Expansion Custom Level': b'ZMCx',
    b'Protoss Expansion Custom Level': b'PMCx',
    b'Terran Campaign Easy': b'TLOf',
    b'Terran Campaign Medium': b'TMED',
    b'Terran Campaign Difficult': b'THIf',
    b'Terran Campaign Insane': b'TSUP',
    b'Terran Campaign Area Town': b'TARE',
    b'Zerg Campaign Easy': b'ZLOf',
    b'Zerg Campaign Medium': b'ZMED',
    b'Zerg Campaign Difficult': b'ZHIf',
    b'Zerg Campaign Insane': b'ZSUP',
    b'Zerg Campaign Area Town': b'ZARE',
    b'Protoss Campaign Easy': b'PLOf',
    b'Protoss Campaign Medium': b'PMED',
    b'Protoss Campaign Difficult': b'PHIf',
    b'Protoss Campaign Insane': b'PSUP',
    b'Protoss Campaign Area Town': b'PARE',
    b'Expansion Terran Campaign Easy': b'TLOx',
    b'Expansion Terran Campaign Medium': b'TMEx',
    b'Expansion Terran Campaign Difficult': b'THIx',
    b'Expansion Terran Campaign Insane': b'TSUx',
    b'Expansion Terran Campaign Area Town': b'TARx',
    b'Expansion Zerg Campaign Easy': b'ZLOx',
    b'Expansion Zerg Campaign Medium': b'ZMEx',
    b'Expansion Zerg Campaign Difficult': b'ZHIx',
    b'Expansion Zerg Campaign Insane': b'ZSUx',
    b'Expansion Zerg Campaign Area Town': b'ZARx',
    b'Expansion Protoss Campaign Easy': b'PLOx',
    b'Expansion Protoss Campaign Medium': b'PMEx',
    b'Expansion Protoss Campaign Difficult': b'PHIx',
    b'Expansion Protoss Campaign Insane': b'PSUx',
    b'Expansion Protoss Campaign Area Town': b'PARx',
    b'Send All Units on Strategic Suicide Missions': b'Suic',
    b'Send All Units on Random Suicide Missions': b'SuiR',
    b'Switch Computer Player to Rescue Passive': b'Rscu',
    b'Turn ON Shared Vision for Player 1': b'+Vi0',
    b'Turn ON Shared Vision for Player 2': b'+Vi1',
    b'Turn ON Shared Vision for Player 3': b'+Vi2',
    b'Turn ON Shared Vision for Player 4': b'+Vi3',
    b'Turn ON Shared Vision for Player 5': b'+Vi4',
    b'Turn ON Shared Vision for Player 6': b'+Vi5',
    b'Turn ON Shared Vision for Player 7': b'+Vi6',
    b'Turn ON Shared Vision for Player 8': b'+Vi7',
    b'Turn OFF Shared Vision for Player 1': b'-Vi0',
    b'Turn OFF Shared Vision for Player 2': b'-Vi1',
    b'Turn OFF Shared Vision for Player 3': b'-Vi2',
    b'Turn OFF Shared Vision for Player 4': b'-Vi3',
    b'Turn OFF Shared Vision for Player 5': b'-Vi4',
    b'Turn OFF Shared Vision for Player 6': b'-Vi5',
    b'Turn OFF Shared Vision for Player 7': b'-Vi6',
    b'Turn OFF Shared Vision for Player 8': b'-Vi7',
    b'Move Dark Templars to Region': b'MvTe',
    b'Clear Previous Combat Data': b'ClrC',
    b'Set Player to Enemy': b'Enmy',
    b'Set Player to Ally  ': b'y   ',
    b'Value This Area Higher': b'VluA',
    b'Enter Closest Bunker': b'EnBk',
    b'Set Generic Command Target': b'StTg',
    b'Make These Units Patrol': b'StPt',
    b'Enter Transport': b'EnTr',
    b'Exit Transport': b'ExTr',
    b'AI Nuke Here': b'NuHe',
    b'AI Harass Here': b'HaHe',
    b'Set Unit Order To: Junk Yard Dog': b'JYDg',
    b'Disruption Web Here': b'DWHe',
    b'Recall Here': b'ReHe',

    # StarCraft AI Scripts
    b'Terran 3 - Zerg Town': b'Ter3',
    b'Terran 5 - Terran Main Town': b'Ter5',
    b'Terran 5 - Terran Harvest Town': b'Te5H',
    b'Terran 6 - Air Attack Zerg': b'Ter6',
    b'Terran 6 - Ground Attack Zerg': b'Te6b',
    b'Terran 6 - Zerg Support Town': b'Te6c',
    b'Terran 7 - Bottom Zerg Town': b'Ter7',
    b'Terran 7 - Right Zerg Town': b'Te7s',
    b'Terran 7 - Middle Zerg Town': b'Te7m',
    b'Terran 8 - Confederate Town': b'Ter8',
    b'Terran 9 - Light Attack': b'Tr9L',
    b'Terran 9 - Heavy Attack': b'Tr9H',
    b'Terran 10 - Confederate Towns': b'Te10',
    b'Terran 11 - Zerg Town': b'T11z',
    b'Terran 11 - Lower Protoss Town': b'T11a',
    b'Terran 11 - Upper Protoss Town': b'T11b',
    b'Terran 12 - Nuke Town': b'T12N',
    b'Terran 12 - Phoenix Town': b'T12P',
    b'Terran 12 - Tank Town': b'T12T',
    b'Terran 1 - Electronic Distribution': b'TED1',
    b'Terran 2 - Electronic Distribution': b'TED2',
    b'Terran 3 - Electronic Distribution': b'TED3',
    b'Terran 1 - Shareware': b'TSW1',
    b'Terran 2 - Shareware': b'TSW2',
    b'Terran 3 - Shareware': b'TSW3',
    b'Terran 4 - Shareware': b'TSW4',
    b'Terran 5 - Shareware': b'TSW5',
    b'Zerg 1 - Terran Town': b'Zer1',
    b'Zerg 2 - Protoss Town': b'Zer2',
    b'Zerg 3 - Terran Town': b'Zer3',
    b'Zerg 4 - Right Terran Town': b'Zer4',
    b'Zerg 4 - Lower Terran Town': b'Ze4S',
    b'Zerg 6 - Protoss Town': b'Zer6',
    b'Zerg 7 - Air Town': b'Zr7a',
    b'Zerg 7 - Ground Town': b'Zr7g',
    b'Zerg 7 - Support Town': b'Zr7s',
    b'Zerg 8 - Scout Town': b'Zer8',
    b'Zerg 8 - Templar Town': b'Ze8T',
    b'Zerg 9 - Teal Protoss': b'Zer9',
    b'Zerg 9 - Left Yellow Protoss': b'Z9ly',
    b'Zerg 9 - Right Yellow Protoss': b'Z9ry',
    b'Zerg 9 - Left Orange Protoss': b'Z9lo',
    b'Zerg 9 - Right Orange Protoss': b'Z9ro',
    b'Zerg 10 - Left Teal (Attack': b'Z10a',
    b'Zerg 10 - Right Teal (Support': b'Z10b',
    b'Zerg 10 - Left Yellow (Support': b'Z10c',
    b'Zerg 10 - Right Yellow (Attack': b'Z10d',
    b'Zerg 10 - Red Protoss': b'Z10e',
    b'Protoss 1 - Zerg Town': b'Pro1',
    b'Protoss 2 - Zerg Town': b'Pro2',
    b'Protoss 3 - Air Zerg Town': b'Pr3R',
    b'Protoss 3 - Ground Zerg Town': b'Pr3G',
    b'Protoss 4 - Zerg Town': b'Pro4',
    b'Protoss 5 - Zerg Town Island': b'Pr5I',
    b'Protoss 5 - Zerg Town Base': b'Pr5B',
    b'Protoss 7 - Left Protoss Town': b'Pro7',
    b'Protoss 7 - Right Protoss Town': b'Pr7B',
    b'Protoss 7 - Shrine Protoss': b'Pr7S',
    b'Protoss 8 - Left Protoss Town': b'Pro8',
    b'Protoss 8 - Right Protoss Town': b'Pr8B',
    b'Protoss 8 - Protoss Defenders': b'Pr8D',
    b'Protoss 9 - Ground Zerg': b'Pro9',
    b'Protoss 9 - Air Zerg': b'Pr9W',
    b'Protoss 9 - Spell Zerg': b'Pr9Y',
    b'Protoss 10 - Mini-Towns': b'Pr10',
    b'Protoss 10 - Mini-Town Master': b'P10C',
    b'Protoss 10 - Overmind Defenders': b'P10o',

    # Brood Wars AI Scripts
    b'Brood Wars Protoss 1 - Town A': b'PB1A',
    b'Brood Wars Protoss 1 - Town B': b'PB1B',
    b'Brood Wars Protoss 1 - Town C': b'PB1C',
    b'Brood Wars Protoss 1 - Town D': b'PB1D',
    b'Brood Wars Protoss 1 - Town E': b'PB1E',
    b'Brood Wars Protoss 1 - Town F': b'PB1F',
    b'Brood Wars Protoss 2 - Town A': b'PB2A',
    b'Brood Wars Protoss 2 - Town B': b'PB2B',
    b'Brood Wars Protoss 2 - Town C': b'PB2C',
    b'Brood Wars Protoss 2 - Town D': b'PB2D',
    b'Brood Wars Protoss 2 - Town E': b'PB2E',
    b'Brood Wars Protoss 2 - Town F': b'PB2F',
    b'Brood Wars Protoss 3 - Town A': b'PB3A',
    b'Brood Wars Protoss 3 - Town B': b'PB3B',
    b'Brood Wars Protoss 3 - Town C': b'PB3C',
    b'Brood Wars Protoss 3 - Town D': b'PB3D',
    b'Brood Wars Protoss 3 - Town E': b'PB3E',
    b'Brood Wars Protoss 3 - Town F': b'PB3F',
    b'Brood Wars Protoss 4 - Town A': b'PB4A',
    b'Brood Wars Protoss 4 - Town B': b'PB4B',
    b'Brood Wars Protoss 4 - Town C': b'PB4C',
    b'Brood Wars Protoss 4 - Town D': b'PB4D',
    b'Brood Wars Protoss 4 - Town E': b'PB4E',
    b'Brood Wars Protoss 4 - Town F': b'PB4F',
    b'Brood Wars Protoss 5 - Town A': b'PB5A',
    b'Brood Wars Protoss 5 - Town B': b'PB5B',
    b'Brood Wars Protoss 5 - Town C': b'PB5C',
    b'Brood Wars Protoss 5 - Town D': b'PB5D',
    b'Brood Wars Protoss 5 - Town E': b'PB5E',
    b'Brood Wars Protoss 5 - Town F': b'PB5F',
    b'Brood Wars Protoss 6 - Town A': b'PB6A',
    b'Brood Wars Protoss 6 - Town B': b'PB6B',
    b'Brood Wars Protoss 6 - Town C': b'PB6C',
    b'Brood Wars Protoss 6 - Town D': b'PB6D',
    b'Brood Wars Protoss 6 - Town E': b'PB6E',
    b'Brood Wars Protoss 6 - Town F': b'PB6F',
    b'Brood Wars Protoss 7 - Town A': b'PB7A',
    b'Brood Wars Protoss 7 - Town B': b'PB7B',
    b'Brood Wars Protoss 7 - Town C': b'PB7C',
    b'Brood Wars Protoss 7 - Town D': b'PB7D',
    b'Brood Wars Protoss 7 - Town E': b'PB7E',
    b'Brood Wars Protoss 7 - Town F': b'PB7F',
    b'Brood Wars Protoss 8 - Town A': b'PB8A',
    b'Brood Wars Protoss 8 - Town B': b'PB8B',
    b'Brood Wars Protoss 8 - Town C': b'PB8C',
    b'Brood Wars Protoss 8 - Town D': b'PB8D',
    b'Brood Wars Protoss 8 - Town E': b'PB8E',
    b'Brood Wars Protoss 8 - Town F': b'PB8F',
    b'Brood Wars Terran 1 - Town A': b'TB1A',
    b'Brood Wars Terran 1 - Town B': b'TB1B',
    b'Brood Wars Terran 1 - Town C': b'TB1C',
    b'Brood Wars Terran 1 - Town D': b'TB1D',
    b'Brood Wars Terran 1 - Town E': b'TB1E',
    b'Brood Wars Terran 1 - Town F': b'TB1F',
    b'Brood Wars Terran 2 - Town A': b'TB2A',
    b'Brood Wars Terran 2 - Town B': b'TB2B',
    b'Brood Wars Terran 2 - Town C': b'TB2C',
    b'Brood Wars Terran 2 - Town D': b'TB2D',
    b'Brood Wars Terran 2 - Town E': b'TB2E',
    b'Brood Wars Terran 2 - Town F': b'TB2F',
    b'Brood Wars Terran 3 - Town A': b'TB3A',
    b'Brood Wars Terran 3 - Town B': b'TB3B',
    b'Brood Wars Terran 3 - Town C': b'TB3C',
    b'Brood Wars Terran 3 - Town D': b'TB3D',
    b'Brood Wars Terran 3 - Town E': b'TB3E',
    b'Brood Wars Terran 3 - Town F': b'TB3F',
    b'Brood Wars Terran 4 - Town A': b'TB4A',
    b'Brood Wars Terran 4 - Town B': b'TB4B',
    b'Brood Wars Terran 4 - Town C': b'TB4C',
    b'Brood Wars Terran 4 - Town D': b'TB4D',
    b'Brood Wars Terran 4 - Town E': b'TB4E',
    b'Brood Wars Terran 4 - Town F': b'TB4F',
    b'Brood Wars Terran 5 - Town A': b'TB5A',
    b'Brood Wars Terran 5 - Town B': b'TB5B',
    b'Brood Wars Terran 5 - Town C': b'TB5C',
    b'Brood Wars Terran 5 - Town D': b'TB5D',
    b'Brood Wars Terran 5 - Town E': b'TB5E',
    b'Brood Wars Terran 5 - Town F': b'TB5F',
    b'Brood Wars Terran 6 - Town A': b'TB6A',
    b'Brood Wars Terran 6 - Town B': b'TB6B',
    b'Brood Wars Terran 6 - Town C': b'TB6C',
    b'Brood Wars Terran 6 - Town D': b'TB6D',
    b'Brood Wars Terran 6 - Town E': b'TB6E',
    b'Brood Wars Terran 6 - Town F': b'TB6F',
    b'Brood Wars Terran 7 - Town A': b'TB7A',
    b'Brood Wars Terran 7 - Town B': b'TB7B',
    b'Brood Wars Terran 7 - Town C': b'TB7C',
    b'Brood Wars Terran 7 - Town D': b'TB7D',
    b'Brood Wars Terran 7 - Town E': b'TB7E',
    b'Brood Wars Terran 7 - Town F': b'TB7F',
    b'Brood Wars Terran 8 - Town A': b'TB8A',
    b'Brood Wars Terran 8 - Town B': b'TB8B',
    b'Brood Wars Terran 8 - Town C': b'TB8C',
    b'Brood Wars Terran 8 - Town D': b'TB8D',
    b'Brood Wars Terran 8 - Town E': b'TB8E',
    b'Brood Wars Terran 8 - Town F': b'TB8F',
    b'Brood Wars Zerg 1 - Town A': b'ZB1A',
    b'Brood Wars Zerg 1 - Town B': b'ZB1B',
    b'Brood Wars Zerg 1 - Town C': b'ZB1C',
    b'Brood Wars Zerg 1 - Town D': b'ZB1D',
    b'Brood Wars Zerg 1 - Town E': b'ZB1E',
    b'Brood Wars Zerg 1 - Town F': b'ZB1F',
    b'Brood Wars Zerg 2 - Town A': b'ZB2A',
    b'Brood Wars Zerg 2 - Town B': b'ZB2B',
    b'Brood Wars Zerg 2 - Town C': b'ZB2C',
    b'Brood Wars Zerg 2 - Town D': b'ZB2D',
    b'Brood Wars Zerg 2 - Town E': b'ZB2E',
    b'Brood Wars Zerg 2 - Town F': b'ZB2F',
    b'Brood Wars Zerg 3 - Town A': b'ZB3A',
    b'Brood Wars Zerg 3 - Town B': b'ZB3B',
    b'Brood Wars Zerg 3 - Town C': b'ZB3C',
    b'Brood Wars Zerg 3 - Town D': b'ZB3D',
    b'Brood Wars Zerg 3 - Town E': b'ZB3E',
    b'Brood Wars Zerg 3 - Town F': b'ZB3F',
    b'Brood Wars Zerg 4 - Town A': b'ZB4A',
    b'Brood Wars Zerg 4 - Town B': b'ZB4B',
    b'Brood Wars Zerg 4 - Town C': b'ZB4C',
    b'Brood Wars Zerg 4 - Town D': b'ZB4D',
    b'Brood Wars Zerg 4 - Town E': b'ZB4E',
    b'Brood Wars Zerg 4 - Town F': b'ZB4F',
    b'Brood Wars Zerg 5 - Town A': b'ZB5A',
    b'Brood Wars Zerg 5 - Town B': b'ZB5B',
    b'Brood Wars Zerg 5 - Town C': b'ZB5C',
    b'Brood Wars Zerg 5 - Town D': b'ZB5D',
    b'Brood Wars Zerg 5 - Town E': b'ZB5E',
    b'Brood Wars Zerg 5 - Town F': b'ZB5F',
    b'Brood Wars Zerg 6 - Town A': b'ZB6A',
    b'Brood Wars Zerg 6 - Town B': b'ZB6B',
    b'Brood Wars Zerg 6 - Town C': b'ZB6C',
    b'Brood Wars Zerg 6 - Town D': b'ZB6D',
    b'Brood Wars Zerg 6 - Town E': b'ZB6E',
    b'Brood Wars Zerg 6 - Town F': b'ZB6F',
    b'Brood Wars Zerg 7 - Town A': b'ZB7A',
    b'Brood Wars Zerg 7 - Town B': b'ZB7B',
    b'Brood Wars Zerg 7 - Town C': b'ZB7C',
    b'Brood Wars Zerg 7 - Town D': b'ZB7D',
    b'Brood Wars Zerg 7 - Town E': b'ZB7E',
    b'Brood Wars Zerg 7 - Town F': b'ZB7F',
    b'Brood Wars Zerg 8 - Town A': b'ZB8A',
    b'Brood Wars Zerg 8 - Town B': b'ZB8B',
    b'Brood Wars Zerg 8 - Town C': b'ZB8C',
    b'Brood Wars Zerg 8 - Town D': b'ZB8D',
    b'Brood Wars Zerg 8 - Town E': b'ZB8E',
    b'Brood Wars Zerg 8 - Town F': b'ZB8F',
    b'Brood Wars Zerg 9 - Town A': b'ZB9A',
    b'Brood Wars Zerg 9 - Town B': b'ZB9B',
    b'Brood Wars Zerg 9 - Town C': b'ZB9C',
    b'Brood Wars Zerg 9 - Town D': b'ZB9D',
    b'Brood Wars Zerg 9 - Town E': b'ZB9E',
    b'Brood Wars Zerg 9 - Town F': b'ZB9F',
    b'Brood Wars Zerg 10 - Town A': b'ZB0A',
    b'Brood Wars Zerg 10 - Town B': b'ZB0B',
    b'Brood Wars Zerg 10 - Town C': b'ZB0C',
    b'Brood Wars Zerg 10 - Town D': b'ZB0D',
    b'Brood Wars Zerg 10 - Town E': b'ZB0E',
    b'Brood Wars Zerg 10 - Town F': b'ZB0F',
}
