#define IFX                              1
#define ELSE                             2
#define ASSIGN                           3
#define QMARK                            4
#define COMMA                            5
#define LOR                              6
#define LAND                             7
#define LNOT                             8
#define EQ                               9
#define LE                              10
#define LT                              11
#define GE                              12
#define GT                              13
#define NE                              14
#define BITOR                           15
#define BITXOR                          16
#define BITAND                          17
#define LSHIFT                          18
#define RSHIFT                          19
#define PLUS                            20
#define MINUS                           21
#define DIVIDE                          22
#define MULTIPLY                        23
#define MOD                             24
#define UNARY                           25
#define BITNOT                          26
#define LPAREN                          27
#define LSQBRACKET                      28
#define PERIOD                          29
#define SEMICOLON                       30
#define NAME                            31
#define IMPORT                          32
#define AS                              33
#define COLON                           34
#define FUNCTION                        35
#define RPAREN                          36
#define OBJECT                          37
#define LBRACKET                        38
#define VAR                             39
#define RBRACKET                        40
#define NUMBER                          41
#define RSQBRACKET                      42
#define SUBSCRIPT                       43
#define KILLS                           44
#define MEMBER                          45
#define STRING                          46
#define FUNCCALL                        47
#define L2V                             48
#define MAPSTRING                       49
#define UNIT                            50
#define SWITCH                          51
#define LOCATION                        52
#define STATIC                          53
#define CONST                           54
#define INC                             55
#define DEC                             56
#define IADD                            57
#define ISUB                            58
#define IMUL                            59
#define IDIV                            60
#define IMOD                            61
#define ILSH                            62
#define IRSH                            63
#define IBND                            64
#define IBOR                            65
#define IBXR                            66
#define ONCE                            67
#define IF                              68
#define SWITCHCASE                      69
#define CASE                            70
#define DEFAULT                         71
#define WHILE                           72
#define FOR                             73
#define FOREACH                         74
#define CONTINUE                        75
#define BREAK                           76
#define RETURN                          77
#define CONDITIONNAME                   78
#define ACTIONNAME                      79
